FROM mcr.microsoft.com/playwright/dotnet:v1.49.0-noble

# .NET 8 SDK (required for build + running tests)
RUN curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0 --install-dir /usr/share/dotnet && \
    ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

WORKDIR /app
COPY . .
# We will run restore/build inside the container when needed or as part of the CMD
# But here we pre-build to cache dependencies
RUN dotnet restore && dotnet build -c Release

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
